# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: rollbackBuildId
  displayName: 'BuildId para rollback (use NONE para execução normal)'
  type: string
  default: 'NONE'

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: cicd-variables

- name: buildConfiguration
  value: 'Release'

- name: projectPath
  value: 'SampleApp/SampleApp.csproj'

- name: artifactName
  value: 'publish'

- name: major
  value: '1'

- name: minor
  value: '0'

stages:
# =========================
# CI
# =========================
- stage: CI
  displayName: 'CI - Build e Testes'
  condition: eq('${{ parameters.rollbackBuildId }}', 'NONE')
  jobs:
  - job: Build
    displayName: 'Build da aplicação'
    steps:
    - checkout: self
      fetchDepth: 0
      persistCredentials: true
    
    - task: UseDotNet@2
      displayName: 'Instalar .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - script: |
        dotnet tool install --global GitVersion.Tool --version '6.*'
        export PATH="$PATH:$HOME/.dotnet/tools"
        dotnet-gitversion /version
      displayName: 'Instalar GitVersion'

    - script: |
        export PATH="$PATH:$HOME/.dotnet/tools"

        VERSION=$(dotnet-gitversion /showvariable MajorMinorPatch)

        echo "Versão calculada pelo GitVersion: $VERSION"
        echo "##vso[task.setvariable variable=appVersion]$VERSION"
        echo "##vso[task.setvariable variable=appVersionOutput;isOutput=true]$VERSION"
      name: GitVersion
      displayName: 'Calcular versão SemVer'

    - script: |
        echo "Versão da aplicação: $(appVersion)"
        echo "BuildId: $(Build.BuildId)"
      displayName: 'Exibir versão da aplicação'
    
    - task: Cache@2
      displayName: 'Cache de pacotes NuGet'
      inputs:
        key: 'nuget | "$(Agent.OS)" | **/*.csproj'
        restoreKeys: |
          nuget | "$(Agent.OS)"
          nuget
        path: '$(HOME)/.nuget/packages'

    - script: dotnet restore $(projectPath)
      displayName: 'Restaurar dependências'

    - task: SonarCloudPrepare@4.2.6
      displayName: 'Preparar análise SonarQube Cloud'
      inputs:
        SonarQube: 'sonarcloud-sc'
        organization: 'renatovitoriok'
        scannerMode: 'dotnet'
        projectKey: 'renatovitoriok_Azure-DevOps-CICD'
        projectName: 'Azure-DevOps-CICD'
        extraProperties: |
          sonar.cs.opencover.reportsPaths=$(Agent.TempDirectory)/TestResults/**/coverage.opencover.xml

    - script: |
        if [ -z "$APP_API_KEY" ]; then
          echo "Secret APP_API_KEY não foi carregado."
          exit 1
        fi

        echo "Secret APP_API_KEY carregado com sucesso."
      displayName: 'Validar secret da pipeline'
      env:
        APP_API_KEY: $(APP_API_KEY)

    - script: |
        dotnet build $(projectPath) \
          --configuration $(buildConfiguration) \
          --no-restore \
          -p:Version=$(appVersion) \
          -p:AssemblyVersion=$(appVersion).0 \
          -p:FileVersion=$(appVersion).0 \
          /warnaserror
      displayName: 'Compilar aplicação com análise de qualidade'

    - script: |
        dotnet test SampleApp.Tests/SampleApp.Tests.csproj \
          --configuration $(buildConfiguration) \
          -p:Version=$(appVersion) \
          -p:AssemblyVersion=$(appVersion).0 \
          -p:FileVersion=$(appVersion).0 \
          --collect:"XPlat Code Coverage;Format=cobertura,opencover" \
          --results-directory "$(Agent.TempDirectory)/TestResults"
      displayName: 'Executar testes com cobertura'

    - task: PublishCodeCoverageResults@2
      displayName: 'Publicar cobertura de testes'
      inputs:
        summaryFileLocation: '$(Agent.TempDirectory)/TestResults/**/coverage.cobertura.xml'

    - task: SonarCloudAnalyze@4.2.6
      displayName: 'Executar análise SonarQube Cloud'

    - task: SonarCloudPublish@4.2.6
      displayName: 'Publicar Quality Gate SonarQube Cloud'
      inputs:
        pollingTimeoutSec: '300'

    - script: dotnet publish $(projectPath) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build
      displayName: 'Publicar aplicação'

    - script: |
        cp "$(Build.SourcesDirectory)/SampleApp/Dockerfile" "$(Build.ArtifactStagingDirectory)/Dockerfile"

        docker build \
          -t sampleapp:$(Build.BuildId) \
          -t sampleapp:$(appVersion) \
          "$(Build.ArtifactStagingDirectory)"
      displayName: 'Criar imagem Docker'

    - script: |
        echo "Versão SemVer: sampleapp:$(appVersion)"
        echo "Versão técnica: sampleapp:$(Build.BuildId)"
        docker images sampleapp
      displayName: 'Validar versões da imagem Docker'

    - script: |
        docker save \
          -o "$(Build.ArtifactStagingDirectory)/sampleapp-$(Build.BuildId).tar" \
          sampleapp:$(Build.BuildId)
      displayName: 'Salvar imagem Docker'

    - task: PublishPipelineArtifact@1
      displayName: 'Publicar imagem Docker'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/sampleapp-$(Build.BuildId).tar'
        artifact: 'docker-image'

    - task: PublishPipelineArtifact@1
      displayName: 'Publicar artefato'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: '$(artifactName)'

# =========================
# TERRAFORM
# =========================
- stage: TERRAFORM
  displayName: 'Terraform - Validar e Planejar'
  dependsOn: CI
  condition: and(succeeded(), eq('${{ parameters.rollbackBuildId }}', 'NONE'))

  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Init, Validate e Plan'

    steps:
    - checkout: self

    - script: |
        sudo apt-get update
        sudo apt-get install -y gnupg software-properties-common curl

        curl -fsSL https://apt.releases.hashicorp.com/gpg | \
          gpg --dearmor | \
          sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
          sudo tee /etc/apt/sources.list.d/hashicorp.list

        sudo apt-get update
        sudo apt-get install -y terraform

        terraform --version
      displayName: 'Instalar Terraform'

    - task: AzureCLI@2
      displayName: 'Terraform Init, Validate e Plan'
      inputs:
        azureSubscription: 'azure-terraform-sc'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: '$(Build.SourcesDirectory)/terraform'
        inlineScript: |
          terraform init
          terraform validate
          terraform plan -out=tfplan

    - task: PublishPipelineArtifact@1
      displayName: 'Publicar Terraform Plan'
      inputs:
        targetPath: '$(Build.SourcesDirectory)/terraform/tfplan'
        artifact: 'terraform-plan'

# =========================
# TERRAFORM APPLY
# =========================
- stage: TERRAFORM_APPLY
  displayName: 'Terraform - Aplicar Infraestrutura'
  dependsOn: TERRAFORM
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq('${{ parameters.rollbackBuildId }}', 'NONE'))

  jobs:
  - deployment: TerraformApply
    displayName: 'Terraform Apply'
    environment: 'Terraform-Apply'

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - download: current
            artifact: 'terraform-plan'

          - script: |
              sudo apt-get update
              sudo apt-get install -y gnupg software-properties-common curl

              curl -fsSL https://apt.releases.hashicorp.com/gpg | \
                gpg --dearmor | \
                sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

              echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
                sudo tee /etc/apt/sources.list.d/hashicorp.list

              sudo apt-get update
              sudo apt-get install -y terraform

              terraform --version
            displayName: 'Instalar Terraform'

          - task: AzureCLI@2
            displayName: 'Terraform Apply'
            inputs:
              azureSubscription: 'azure-terraform-sc'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              workingDirectory: '$(Build.SourcesDirectory)/terraform'
              inlineScript: |
                terraform init
                terraform apply "$(Pipeline.Workspace)/terraform-plan/tfplan"

# =========================
# HML
# =========================
- stage: HML
  displayName: 'Deploy HML'
  dependsOn: CI
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq('${{ parameters.rollbackBuildId }}', 'NONE'))

  variables:
    appVersion: $[ stageDependencies.CI.Build.outputs['GitVersion.appVersionOutput'] ]
    
  jobs:
  - deployment: DeployHML
    displayName: 'Deploy da aplicação em HML'
    environment: HML

    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/deploy-docker.yml
            parameters:
              containerName: 'sampleapp-hml'
              environmentName: 'HML'

# =========================
# PRD
# =========================
- stage: PRD
  displayName: 'Deploy PRD'
  dependsOn: 
  - HML
  - CI
  
  condition: and(succeeded(), eq('${{ parameters.rollbackBuildId }}', 'NONE'))

  variables:
    appVersion: $[ stageDependencies.CI.Build.outputs['GitVersion.appVersionOutput'] ]

  jobs:
  - deployment: DeployPRD
    displayName: 'Deploy da aplicação em PRD'
    environment: PRD

    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/deploy-docker.yml
            parameters:
              containerName: 'sampleapp-prd'
              environmentName: 'PRD'

# =========================
# TAG
# =========================
- stage: TAG
  displayName: 'Criar tag da versão'
  dependsOn:
  - PRD
  - CI

  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq('${{ parameters.rollbackBuildId }}', 'NONE'))

  variables:
    appVersion: $[ stageDependencies.CI.Build.outputs['GitVersion.appVersionOutput'] ]

  jobs:
  - job: CreateTag
    displayName: 'Criar tag Git'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      fetchDepth: 0
      persistCredentials: true

    - script: |
        TAG="v$(appVersion)"

        echo "Versão: $(appVersion)"
        echo "Tag que será criada: $TAG"

        git config user.name "Azure DevOps Pipeline"
        git config user.email "pipeline@azuredevops.local"

        if git rev-parse "$TAG" >/dev/null 2>&1; then
          echo "A tag $TAG já existe. Nenhuma ação necessária."
          exit 0
        fi

        git tag -a "$TAG" -m "Release $TAG"
        git push origin "$TAG"
      displayName: 'Criar e publicar tag'

# =========================
# ROLLBACK
# =========================
- stage: ROLLBACK
  displayName: 'Rollback'
  dependsOn: []
  condition: ne('${{ parameters.rollbackBuildId }}', 'NONE')

  jobs:
  - job: Rollback
    displayName: 'Executar Rollback'

    steps:
    - script: |
        echo "Rollback solicitado."
        echo "BuildId selecionado: ${{ parameters.rollbackBuildId }}"
      displayName: 'Identificar versão para rollback'

    - template: templates/rollback-docker.yml
      parameters:
        containerName: 'sampleapp-rollback'
        environmentName: 'HML'
        rollbackBuildId: '${{ parameters.rollbackBuildId }}'

# =========================
# ROLLBACK PRD
# =========================
- stage: ROLLBACK_PRD
  displayName: 'Rollback PRD'
  dependsOn: ROLLBACK
  condition: and(succeeded(), ne('${{ parameters.rollbackBuildId }}', 'NONE'))

  jobs:
  - deployment: RollbackPRD
    displayName: 'Aplicar rollback em PRD'
    environment: PRD

    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/rollback-docker.yml
            parameters:
              containerName: 'sampleapp-rollback-prd'
              environmentName: 'PRD'
              rollbackBuildId: '${{ parameters.rollbackBuildId }}'
